numbers = [12,45,98,68,71]
numbers.append(56)
numbers.insert(1,100)
print(numbers)
numbers.remove(98)
print(numbers)
last = numbers.pop()
print(last,numbers)
index = numbers.index(12)
print(index)
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)